export function renderThirdPartyOperatorPlaybookTemplate(): string {
  return [
    "# Operator Playbook",
    "",
    "This file is the repository-owned operator policy companion to `WORKFLOW.md` and `AGENTS.md`.",
    "",
    "Use it to document repo-specific operator rules that should be reviewable in this repository instead of hidden in engine-global operator prompts.",
    "",
    "## Required Customization",
    "",
    "Review and tailor this file before you rely on unattended operator wake-ups.",
    "",
    "At minimum, decide and document:",
    "",
    "1. when the operator should post `/land` by default and when landing stays manual",
    "2. whether release dependencies or queue-promotion rules block downstream work",
    "3. what post-merge refresh and detached-runtime restart policy this repository expects",
    "4. what counts as a normal operator intervention versus an escalation for this repository",
    "",
    "## Landing Policy",
    "",
    "- State whether the operator should post `/land` automatically once CI is green and review is clean.",
    "- List any repository-specific required reviews, bot approvals, or manual hold points.",
    "",
    "## Release And Queue Policy",
    "",
    "- Describe any prerequisite issue or release gating rules before promoting downstream work or landing dependent PRs.",
    "- If this repository does not use release gating yet, say that explicitly.",
    "",
    "## Post-Merge Refresh Policy",
    "",
    "- Describe whether the operator should fast-forward the selected instance root after merges.",
    "- Describe when the detached runtime should restart, for example only when the runtime checkout or selected `WORKFLOW.md` is stale.",
    "",
    "## Intervention And Escalation Policy",
    "",
    "- Document which operator actions are normal for this repository, such as plan review, `/land`, or routine runtime restarts.",
    "- Document which situations require a pause, human escalation, or a tracked follow-up issue.",
    "",
    "Keep runtime correctness in code and tests. Use this playbook for repo-owned operator policy, not for behavior that the runtime must enforce mechanically.",
    "",
  ].join("\n");
}
